### ISSUE TITLE
Headers already sent Exception

### ISSUE THREAD

**Issue by odai-alali** [dektrium/yii2-rbac#137]
### What steps will reproduce the problem?
Use any form that uses ajax validation method in `ItemControllerAbstract.php`
### What is the expected result?
The form to be submitted
### What do you get instead?
Nothing happens and in the network tab in the chrome devtools the following error is returned
```
An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/dektrium/yii2-rbac/controllers/ItemControllerAbstract.php on line 144. in /app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /app/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /app/vendor/dektrium/yii2-rbac/controllers/ItemControllerAbstract.php on line 144. in /app/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /app/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /app/vendor/yiisoft/yii2/base/Application.php(656): yii\web\Response->send()
#2 /app/vendor/dektrium/yii2-rbac/controllers/ItemControllerAbstract.php(145): yii\base\Application->end()
#3 /app/vendor/dektrium/yii2-rbac/controllers/ItemControllerAbstract.php(83): dektrium\rbac\controllers\ItemControllerAbstract->performAjaxValidation(Object(dektrium\rbac\models\Permission))
#4 [internal function]: dektrium\rbac\controllers\ItemControllerAbstract->actionCreate()
#5 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('create', Array)
#8 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('rbac/permission...', Array)
#9 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 /app/web/index.php(12): yii\base\Application->run()
#11 {main}
```
### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.15
| Yii2-rbac version | 1.0.0-alpha
| PHP version       | 7.1

**Comment by odai-alali** [comment]
fixed 748453654e69eedadb3aa87ba327f1c554061004
