### ISSUE TITLE
Exception 'yii\base\InvalidConfigException' with message 'You have wrong authManager configuration'

### ISSUE THREAD

**Issue by nandes2062** [dektrium/yii2-rbac#90]
### What steps will reproduce the problem?

> $ ./yii migrate --migrationPath=@yii/rbac/migrations
> 
> Exception 'yii\base\InvalidConfigException' with message 'You have wrong authManager configuration'
> 
> in /opt/www/yiiusuarios/vendor/dektrium/yii2-rbac/Bootstrap.php:49
> 
> Stack trace:
> #0 /opt/www/yiiusuarios/vendor/yiisoft/yii2/base/Application.php(291): dektrium\rbac\Bootstrap->bootstrap(Object(yii\console\Application))
> #1 /opt/www/yiiusuarios/vendor/yiisoft/yii2/base/Application.php(267): yii\base\Application->bootstrap()
> #2 /opt/www/yiiusuarios/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
> #3 /opt/www/yiiusuarios/vendor/yiisoft/yii2/base/Object.php(107): yii\console\Application->init()
> #4 /opt/www/yiiusuarios/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object->__construct(Array)
> #5 /opt/www/yiiusuarios/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
> #6 /opt/www/yiiusuarios/yii(26): yii\console\Application->__construct(Array)
> #7 {main}
> 

ERRORR IN MIGRATIONS dektrium/yii2-rbac/Bootstrap.php:49,,, HELP PLEASE...

**Comment by turboezh** [comment]
Your authManager must implement `\dektrium\rbac\components\ManagerInterface`, not `\yii\rbac\ManagerInterface`. You may extend it from `\dektrium\rbac\components\DbManager` instead of `\yii\rbac\DbManager`.

**Comment by exneval** [comment]
@dmeroff 
@turboezh 
facing the same issue, related to #85 
But the only different is my error is
`Exception 'yii\base\InvalidConfigException' with message 'You should configure "authManager" component to use database before executing this migration.'`
use latest branch master and yii2-advanced-app
and there's no documentation about yii2-advanced-app

**Comment by zxx1988328** [comment]
I edited the code 
```
'rbac' => [
        //  'class' => 'dektrium\rbac\Module',//old code
            'class' => 'dektrium\rbac\RbacWebModule',//new code 
        ],
```
still got this error  
>You have wrong authManager configuration

 after using the latest code.
How to solve this problem?

**Comment by exneval** [comment]
You also need to add authmanager component like in #85
